# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
url:            "https://bootstrap-table.com"
encoding:       UTF-8

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

algolia:
  application_id: FXDJ517Z8G
  index_name:     bootstrap-table

# Custom variables
current_version:  1.14.2
title:            "Bootstrap Table"
description:      "An extended Bootstrap Table with radio, checkbox, sort, pagination, and other added features."
authors:          "Zhixin Wen, and Bootstrap Table contributors"
keywords:         "table, bootstrap, bootstrap plugin, bootstrap resources, bootstrap table, jQuery plugin"
repo:             https://github.com/wenzhixin/bootstrap-table
website:          http://wenzhixin.net.cn
repos:            http://repos.wenzhixin.net.cn
email:            wenzhixin2010@gmail.com
twitter:          wenzhixin2010
opencollective:   bootstrap-table
master_zip:       https://github.com/wenzhixin/bootstrap-table/archive/master.zip

toc:
  min_level:      2
  max_level:      4
