# Dependencies
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - tables
  - autolink
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             4000
url:              http://bootstrap-table.wenzhixin.net.cn
encoding:         UTF-8

# Languages
languages: ["en", "zh-cn", "es"]
languages_string: ["English", "简体中文", "Español"]

# Custom vars
current_version: 1.7.0
repo: https://github.com/wenzhixin/bootstrap-table
website: http://wenzhixin.net.cn
repos: http://repos.wenzhixin.net.cn
email: wenzhixin2010@gmail.com
master_zip: https://github.com/wenzhixin/bootstrap-table/archive/master.zip